name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: run tests
        run: npx cypress run --spec "cypress/e2e/login.cy.js" >> results.text

      - name: read results
        # run: head -n 51 results.text | tail -1 >> $GITHUB_ENV
        run: echo "CYPRESS_PASSED:1" >> $GITHUB_ENV

      - name: Post results to Slack
        uses: rtCamp/action-slack-notify@v2.1.1
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          status: 'completed'
          color: ${{ job.status == 'success' && '#36a64f' || '#ff0000' }}
          fields: |
            Tests Passed: ${{ env.CYPRESS_PASSED }}
            Tests Failed: ${{ env.CYPRESS_FAILED }}
          channel: '#cypress_is_the_best'

      - name: print me
        run: ls -la