name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          browser: firefox
          spec: cypress/e2e/login.cy.js
          record: true
        env:
          CYPRESS_RECORD_KEY: I_am_the_smartest_key_around
          CYPRESS_PROJECT_ID: 123

      - name: print me
        run: ls -la