name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: npm Install
        run: npm i
        
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: run tests
        run: npx cypress run --spec "cypress/e2e/login.cy.js" >> results.text

      - name: read results
        # run: head -n 51 results.text | tail -1 >> $GITHUB_ENV
        run: echo "CYPRESS_PASSED=$(head -n 51 results.text | tail -1)" >> $GITHUB_ENV

      - name: Post results to Slack
        uses: rtCamp/action-slack-notify@v2.1.1
        env:
          SLACK_CHANNEL: general
          SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          # SLACK_MESSAGE: ${{ env.CYPRESS_PASSED }}
          SLACK_MESSAGE: 'Post Content :rocket:'
          SLACK_TITLE: Post Title
          SLACK_USERNAME: slack
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}


      - name: print me
        run: ls -la